# -*- coding:utf-8 -*-
from typing import Literal, Optional, Any

from openpyxl.cell import Cell
from openpyxl.styles import Alignment, Font, Border, Fill, NumberFormatDescriptor, Protection, Side

LINES = Literal['dashDot', 'dashDotDot', 'dashed', 'dotted', 'double', 'hair', 'medium', 'mediumDashDot',
'mediumDashDotDot', 'mediumDashed', 'slantDashDot', 'thick', 'thin', None]


class CellStyle(object):
    font_args: tuple = ...
    border_args: tuple = ...

    def __init__(self) -> None:
        self._style = ...
        self._font = ...
        self._border = ...
        self._fill = ...
        self._number_format = ...
        self._protection = ...
        self._alignment = ...

    @property
    def font(self) -> CellFont: ...

    @property
    def border(self) -> CellBorder: ...

    @property
    def alignment(self) -> CellAlignment: ...

    def to_cell(self, cell: Cell) -> None: ...


def _handle_args(args: tuple, src: Any, target: Any) -> dict: ...


class CellFont(object):
    LINE_STYLES: tuple = ...
    SCHEMES: tuple = ...
    VERT_ALIGNS: tuple = ...

    def __init__(self):
        self.name: str = ...
        self.charset: int = ...
        self.size: float = ...
        self.bold: bool = ...
        self.italic: bool = ...
        self.strike: bool = ...
        self.outline: bool = ...
        self.shadow: bool = ...
        self.condense: bool = ...
        self.extend: bool = ...
        self.underline: Literal['single', 'double', 'singleAccounting', 'doubleAccounting'] = ...
        self.vertAlign: Literal['superscript', 'subscript', 'baseline'] = ...
        self.color: str = ...
        self.scheme: Literal['major', 'minor'] = ...

    def set_name(self, name: Optional[str]) -> None: ...

    def set_charset(self, charset: Optional[int]) -> None: ...

    def set_size(self, size: Optional[float]) -> None: ...

    def set_bold(self, on_off: Optional[bool]) -> None: ...

    def set_italic(self, on_off: Optional[bool]) -> None: ...

    def set_strike(self, on_off: Optional[bool]) -> None: ...

    def set_outline(self, on_off: Optional[bool]) -> None: ...

    def set_shadow(self, on_off: Optional[bool]) -> None: ...

    def set_condense(self, on_off: Optional[bool]) -> None: ...

    def set_extend(self, on_off: Optional[bool]) -> None: ...

    def set_color(self, color: Optional[str]) -> None: ...

    def set_underline(self,
                      option: Literal['single', 'double', 'singleAccounting', 'doubleAccounting', None]) -> None: ...

    def set_vertAlign(self, option: Literal['superscript', 'subscript', 'baseline', None]) -> None: ...

    def set_scheme(self, option: Literal['major', 'minor', None]) -> None: ...


class CellBorder(object):
    LINE_STYLES: tuple = ...

    def __init__(self):
        self.start: Side = ...
        self.end: Side = ...
        self.left: Side = ...
        self.right: Side = ...
        self.top: Side = ...
        self.bottom: Side = ...
        self.diagonal: Side = ...
        self.vertical: Side = ...
        self.horizontal: Side = ...
        self.horizontal: Side = ...
        self.outline: bool = ...
        self.diagonalUp: bool = ...
        self.diagonalDown: bool = ...

    def set_start(self, style: LINES, color: Optional[str]) -> None: ...

    def set_end(self, style: LINES, color: Optional[str]) -> None: ...

    def set_left(self, style: LINES, color: Optional[str]) -> None: ...

    def set_right(self, style: LINES, color: Optional[str]) -> None: ...

    def set_top(self, style: LINES, color: Optional[str]) -> None: ...

    def set_bottom(self, style: LINES, color: Optional[str]) -> None: ...

    def set_diagonal(self, style: LINES, color: Optional[str]) -> None: ...

    def set_vertical(self, style: LINES, color: Optional[str]) -> None: ...

    def set_horizontal(self, style: LINES, color: Optional[str]) -> None: ...

    def set_outline(self, on_off: bool) -> None: ...

    def set_diagonalDown(self, on_off: bool) -> None: ...

    def set_diagonalUp(self, on_off: bool) -> None: ...


class CellAlignment(object): ...
