# -*- coding:utf-8 -*-
from pathlib import Path
from typing import Union

from openpyxl.cell import Cell
from openpyxl.styles import Alignment, Font, Fill, Border, NumberFormatDescriptor, Protection


class CellStyle(object):
    def __init__(self, from_cell: Cell = None) -> None:
        self._style = ...
        self._font = ...
        self._border = ...
        self._fill = ...
        self._number_format = ...
        self._protection = ...
        self._alignment = ...

    def set_alignment(self, alignment: Alignment) -> None: ...

    def set_font(self, font: Font) -> None: ...

    def set_border(self, border: Border) -> None: ...

    def set_fill(self, fill: Fill) -> None: ...

    def set_number_format(self, number_format: NumberFormatDescriptor) -> None: ...

    def set_protection(self, protection: Protection) -> None: ...

    def to_cell(self, cell: Cell) -> None: ...


def align_csv(path: Union[str, Path], encoding: str = 'utf-8', delimiter: str = ',', quotechar: str = '"') -> None: ...


def get_usable_path(path: Union[str, Path]) -> Path: ...


def make_valid_file_name(full_name: str) -> str: ...
